apiVersion: v1
kind: Secret
metadata:
  name: provider-openstack-config
  namespace: crossplane-system
type: Opaque
data:
  config: ewogICJhdXRoX3VybCI6ICJodHRwOi8vMTAuMTAuMTQuMTgyOjUwMDAiLAogICJhcHBsaWNhdGlvbl9jcmVkZW50aWFsX2lkIjogIjg0ZTNkN2I1OTBjOTQzOTJhNDg4ODE2ZTE1N2ViZTMzIiwKICAiYXBwbGljYXRpb25fY3JlZGVudGlhbF9zZWNyZXQiOiAiSTY5Ulk3bG8zOXl5V3dheGhyVW5NSUw4UEdsX0RGNlJ4MnU1dXNqNzJwR0NMZ04tcmxWWVZ0UVhld3oxaEhPX2VXSkRLZGVtd08zcnhKajNyaHlZVUEiLAogICJpbnNlY3VyZSI6ICJ0cnVlIiwKICAicmVnaW9uIjogIlJlZ2lvbk9uZSIKfQo=
